apiVersion: apps/v1
kind: Deployment
metadata:
  name: qvfdvre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qvfdvre
  template:
    metadata:
      labels:
        app: qvfdvre
    spec:
      containers:
      - image: okteto.dev/qvfdvre:latest
        name: qvfdvre
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "55eb36a7-3473-4dbf-a333-faa9aa2fe490"
        - name: Vless_Path
          value: "/vl5grefd55"
        - name: Vmess_UUID
          value: "55eb36a7-3473-4dbf-a333-faa9aa2fe490"
        - name: Vmess_Path
          value: "/vm6regrfd66"
        - name: Share_Path
          value: "/v2link"
